included:
  - ExchangeRates
  - ExchangeRatesTests

excluded:
  - Pods

whitelist_rules:
    - attributes
    - class_delegate_protocol
    - closing_brace
    - closure_end_indentation
    - closure_spacing
    - colon
    - comma
    - cyclomatic_complexity
    - empty_count
    - empty_parameters
    - empty_parentheses_with_trailing_closure
    - explicit_init
    - first_where
    - force_cast
    - force_try
    - force_unwrapping
    - implicitly_unwrapped_optional
    - implicit_getter
    - leading_whitespace
    - legacy_cggeometry_functions
    - legacy_constant
    - legacy_constructor
    - legacy_nsgeometry_functions
    - opening_brace
    - operator_usage_whitespace
    - redundant_discardable_let
    - redundant_nil_coalescing
    - redundant_void_return
    - return_arrow_whitespace
    - shorthand_operator
    - statement_position
    - syntactic_sugar
    - trailing_comma
    - trailing_newline
    - trailing_semicolon
    - trailing_whitespace
    - vertical_whitespace
    - void_return
    - weak_delegate
    - custom_rules

custom_rules:
  image_name_initialization: # Disable UIImage init from name
      included: ".*.swift"
      name: "Image initialization"
      regex: 'UIImage\(named:[^)]+\)'
      message: "Use UIImage(assetName: ) instead"
      severity: error

  realm_in_ui:
      included: "Screens/.*.swift|User Stories/.*.swift"
      name: "Realm can be used only in services"
      regex: "Realm"
      message: "Realm can be used only in serivces"
      severity: error

  disclosure_of_view_details:
    included: ".*ViewOutput.swift|.*ViewInput.swift"
    name: "Details opening in View protocols"
    regex: "cell|Cell|button|Button|Table|tableView"
    message: "The disclosure of details the implementation should be avoided"
    severity: error

  view_protocol_error:
    included: ".*ViewOutput.swift|.*ViewInput.swift"
    name: "Property in view protocol"
    regex: " var "
    message: "View protocol should contains only methods"
    severity: error

  router_protocol_error:
    included: ".*RouterInput.swift"
    name: "View in Router protocol"
    regex: "view|View"
    message: "Router protocol methods should contains `Module` instead `View`"
    severity: error

  open_iboutlets:
    included: ".*.swift"
    name: "IBOutlet opening"
    regex: "@IBOutlet weak var"
    message: "IBOutlet should be private or fileprivate"
    severity: error

  open_ibaction:
    included: ".*.swift"
    name: "IBAction opening"
    regex: "@IBAction func"
    message: "IBAction should be private or fileprivate"
    severity: error

reporter: "xcode"